import { test, expect } from '@playwright/test';
test('craft, return, persist, and deteriorate', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'こもれびの巣' })).toBeVisible();
  await expect(page.locator('.scene-art')).toHaveJSProperty('naturalWidth', 1086);
  await page.getByRole('button', { name: '住処', exact: true }).click();
  await page.getByRole('button', { name: 'これをつくろう', exact: true }).click();
  await page.getByRole('button', { name: 'ホーム', exact: true }).click();
  await page.getByRole('button', { name: '設定と試作モード' }).click();
  await page.getByRole('button', { name: '離れた時間を試す（2時間）', exact: true }).click();
  await page.getByRole('button', { name: '住処に戻る', exact: true }).click();
  await expect(page.getByRole('heading', { name: '宝物の小さな棚が、できていた。' })).toBeVisible();
  await page.getByRole('button', { name: '住処をのぞく' }).click();
  await expect(page.getByRole('dialog', { name: 'おかえり', exact: true })).toBeHidden();
  await page.reload();
  await page.getByRole('button', { name: '住処', exact: true }).click();
  await expect(page.getByRole('button', { name: 'できあがり', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'ホーム', exact: true }).click();
  await page.getByRole('button', { name: '設定と試作モード' }).click();
  await page.getByRole('button', { name: '使いすぎた状態を試す（2時間）', exact: true }).click();
  await page.getByRole('button', { name: '使いすぎた状態を試す（2時間）', exact: true }).click();
  await page.getByRole('button', { name: '住処に戻る', exact: true }).click();
  await expect(page.locator('.scene-art')).toHaveAttribute('src', '/art/weary.png');
  await expect(page.locator('.scene-art')).toHaveJSProperty('naturalWidth', 1086);
  await page.getByRole('button', { name: '記録', exact: true }).click();
  await expect(page.getByRole('heading', { name: '宝物の小さな棚が、できていた。' })).toBeVisible();
  expect(errors).toEqual([]);
});
